import type { Metadata } from "next";
import { DM_Sans, Montserrat, Poppins } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["700"],
});

const dmsans = DM_Sans({
  variable: "--font-dmsans",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Simple Animated Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${poppins.variable} ${dmsans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
